/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import java.awt.BorderLayout;
import java.io.*;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author radhe
 */
public class FrontPage extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public static MainLogin login;
    public static Registration register;
    public static SplashPage obj;
    public static FrontPage front;
    public static UserView uv;
    static Register R;
    public final String fileDir = "event";
    public final String fileName = "event\\temp.txt";
    public final String picDir = "event\\pics";
    public static ClientConnect cc;
    
    public FrontPage() {
        initComponents();
        
        //cc = new ClientConnect();
        System.out.println("dir created bc");
        
        
        
        File dir = new File(fileDir);
        if(!dir.exists()){
            if(dir.mkdir()){
                System.out.println("dir created");
                File file = new File(fileName);
                if(!file.exists()){
                    try {
                        
                        
                        file.createNewFile();
                        System.out.println("file created");
                    
                    
                    } catch (IOException ex) {
                        Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        else{
            File file = new File(fileName);
                if(!file.exists()){
                    try {
                        
                        
                        file.createNewFile();
                        System.out.println("file created");
                    
                    
                    } catch (IOException ex) {
                        Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
        
        System.out.println("dir created mc");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        
            front= new FrontPage(); 
            cc = new ClientConnect(front);
            
            uv = new UserView(cc);
            obj = new SplashPage();
        
        
            
        System.out.println("dir creatdvzdved");
           
            front.setLocationRelativeTo(null);
            front.setLayout(new BorderLayout());
            front.add(obj, BorderLayout.CENTER);
            front.pack();
            front.setVisible(true);
            
            
            String str = "Loading Scheduler ";
            
           
            
            
            
            Checker f = new Checker(1);
            Thread t = new Thread(f);
            t.start();
            
            
            
            
            Thread connectBack = new Thread(cc);
            connectBack.start();
            
            
            
            BackRequest br = new BackRequest(cc);
            Thread backreq = new Thread(br);
            backreq.start();
            
        
            int j=1;
            for(int i=1; i<=100; i++){
                try {
                    TimeUnit.MILLISECONDS.sleep(35);
                } catch (InterruptedException ex) {
                    Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(i%2==0)
                    str+=".";
                obj.loader.setText(str+" "+j+" %");
                j+=1;
            }
            obj.loader.setText(str+" Completed !");
              
            
            
            
            
            
            
            
        switch (f.p) {
            case 0:
                register = new Registration(uv,cc);
                front.remove(obj);
                front.add(register, BorderLayout.CENTER);
                front.pack();
                front.setVisible(true);
                break;
            case 1:
                login = new MainLogin(uv, cc);
                front.remove(obj);
                front.add(login, BorderLayout.CENTER);
                front.pack();
                front.setVisible(true);
                break;
            case 2:
                front.remove(obj);
                front.add(uv,BorderLayout.CENTER);
                front.pack();
                front.setVisible(true);
                break;
            default:
                break;
        }
           
        
        
        
        
               /* Craete and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
        
             
            
           
            
       // obj.setSize(f, HEIGHT);
                //front.add(s);
                
                //s.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
