/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import static Event.FrontPage.cc;
import static Event.FrontPage.register;
import static Event.FrontPage.uv;
import java.awt.BorderLayout;



/**
 *
 * @author radhe
 */
public class MainLogin extends javax.swing.JPanel {
    
    
    Thread t;
    Login l;
    UserView uv;
    ClientConnect cc;
    /**
     * Creates new form MainLogin
     */
    
    /**
     * Creates new form MainLogin
     * @param uv
     * @param cc
     */
    
    public MainLogin(UserView uv,ClientConnect cc) {
        initComponents();
        this.uv = uv;
        this.cc=cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginpanel = new javax.swing.JPanel();
        uName = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        remember = new javax.swing.JCheckBox();
        error = new javax.swing.JLabel();
        login1 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(75, 172, 198));
        setMaximumSize(new java.awt.Dimension(800, 450));
        setPreferredSize(new java.awt.Dimension(800, 450));

        loginpanel.setBackground(new java.awt.Color(75, 172, 198));

        uName.setBackground(new java.awt.Color(178, 200, 242));
        uName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        uName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        uName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uNameMouseClicked(evt);
            }
        });
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });

        login.setBackground(new java.awt.Color(33, 150, 243));
        login.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });

        remember.setBackground(new java.awt.Color(75, 172, 198));
        remember.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        remember.setForeground(new java.awt.Color(253, 253, 253));
        remember.setText("Remember me");
        remember.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        remember.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rememberStateChanged(evt);
            }
        });

        error.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        error.setForeground(new java.awt.Color(253, 252, 252));
        error.setText("* Enter your login details.");
        error.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        login1.setBackground(new java.awt.Color(33, 150, 243));
        login1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        login1.setForeground(new java.awt.Color(255, 255, 255));
        login1.setText("Register");
        login1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login1MouseClicked(evt);
            }
        });

        pass.setBackground(new java.awt.Color(178, 200, 242));
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout loginpanelLayout = new javax.swing.GroupLayout(loginpanel);
        loginpanel.setLayout(loginpanelLayout);
        loginpanelLayout.setHorizontalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(error, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addComponent(remember, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(uName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginpanelLayout.createSequentialGroup()
                        .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pass))
                .addContainerGap())
        );
        loginpanelLayout.setVerticalGroup(
            loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(login1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remember))
                .addGap(18, 18, 18)
                .addComponent(error)
                .addGap(30, 30, 30))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/mew.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed
    
    
    
    int chance;
    
    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        // TODO add your handling code here:
        chance=0;
        
        l = new Login(this,uv, cc);
        //System.out.println("login calliing");
        t = new Thread(l);
        //System.out.println("login calliing");
        t.start();
    }//GEN-LAST:event_loginMouseClicked

    
    
    
    private void rememberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rememberStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rememberStateChanged
    
    
    
    
    
    private void uNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uNameMouseClicked
        // TODO add your handling code here:
                if(chance==0){
                    
                    error.setText("*Enter your login details.");
                    loginpanel.repaint();
                    loginpanel.setVisible(true);
                    chance++;
                
                }    
    }//GEN-LAST:event_uNameMouseClicked

    private void login1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login1MouseClicked
        // TODO add your handling code here:
        
        register = new Registration(uv,cc);
                FrontPage.front.remove(this);
                FrontPage.front.add(register, BorderLayout.CENTER);
                FrontPage.front.pack();
                FrontPage.front.setVisible(true);
    }//GEN-LAST:event_login1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel error;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton login;
    public javax.swing.JButton login1;
    public javax.swing.JPanel loginpanel;
    public javax.swing.JPasswordField pass;
    public javax.swing.JCheckBox remember;
    public javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
}
