/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Event;

import static Event.FrontPage.front;
import com.sun.rowset.CachedRowSetImpl;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.Date;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Jayant Kumar Yadav
 */
public class Setting extends javax.swing.JPanel {

    /**
     * Creates new form Setting
     */
    PreparedStatement ps;
    DisableElement de;
    int changes;
    int focusgained;
    ClientConnect cc;
    private CachedRowSetImpl crs;
    
    public Setting(ClientConnect cc) {
        initComponents();
        this.cc =cc;
    
        changes=0;
        focusgained=0;
        de = new DisableElement(settiingForm);
        de.enableComponents(settiingForm, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    public void fillUp(){
    
        String qur = "select * from member where uname='"+cc.uname+"';";
        //DbHandler db = new DbHandler();
        //Connection con = db.retcon();
        //Querry q = new Querry(con);
        //int s = q.update(qur);
        try {
            //ps = con.prepareStatement(qur);
            //ps.setString(1,"rehaan");
            
            
            //ResultSet rs = ps.executeQuery();
            
            
            
            
            cc.getQuerry(qur,2,cc);
                try {
                    Thread.sleep(450);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Searching.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(cc.connected){
                    System.out.println("setting connected");
                    while(!cc.resultOk){
                        System.out.print("");
                    }
                    System.out.println("setting connected");
                    crs = cc.sendResult();
                    
                    if(crs.next()){
                        System.out.println("yo bro");
                        fName.setText(crs.getString("fname"));
                        lName.setText(crs.getString("lname"));
                        email.setText(crs.getString("email"));
                        regNo.setText(crs.getInt("regno")+"");
                        uName.setText(crs.getString("uname"));
                        pswd.setText(crs.getString("password"));
                        yearn.setText(crs.getInt("year")+"");
                        contact.setText(crs.getInt("contact")+"");
                        System.out.println(crs.getString("gender")+"hgchgkhg");
                        gender.setSelectedItem(crs.getString("gender"));
                        access.setSelectedItem(crs.getString("access"));
                        branch.setSelectedItem(crs.getString("branch"));
                        System.out.println(crs.getString("course")+"hgchgkhg");
                        course.setSelectedItem(crs.getString("course"));
                        System.out.println(crs.getDate("dob").getTime()+"hgchgkhg");
                        dob.setDate(new java.util.Date(crs.getDate("dob").getTime()));
                
                    }
                    
                    
                    
                    
            }
            
            
               
                
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    public void setValues(){
    
        String qur = "update member set fname='"+fName.getText()+"', lname='"+lName.getText()+"', regno="+Integer.parseInt(regNo.getText())+", email='"+email.getText()+"', gender='"+gender.getSelectedItem().toString()+"', contact="+Integer.parseInt(contact.getText())+", profile=null, course='"+course.getSelectedItem().toString()+"', branch='"+branch.getSelectedItem().toString()+"', access='"+access.getSelectedItem().toString()+"', year='"+yearn.getText()+"', dob='"+new java.sql.Date(dob.getDate().getTime())+"' where uname='"+cc.uname+"';";
        cc.getQuerry(qur,1,cc);
        try {
            Thread.sleep(100);
        } catch (InterruptedException ex) {
            Logger.getLogger(Searching.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(cc.connected){
            while(!cc.update){
                System.out.print("");
            }
            
            cc.update = false;
            
            
            JDialog.setDefaultLookAndFeelDecorated(true);
            JOptionPane.showConfirmDialog(null, "Your changes are saved !", "Status", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            changes=0;
            
            
        }
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        editSave = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        settiingForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        upload = new javax.swing.JButton();
        contact = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<String>();
        regNo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        pswd = new javax.swing.JTextField();
        uName = new javax.swing.JTextField();
        lName = new javax.swing.JTextField();
        course = new javax.swing.JComboBox<String>();
        branch = new javax.swing.JComboBox<String>();
        year = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        yearn = new javax.swing.JTextField();
        dob = new org.jdesktop.swingx.JXDatePicker();
        access = new javax.swing.JComboBox<String>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        label2.setText("label2");

        setBackground(new java.awt.Color(101, 207, 165));
        setPreferredSize(new java.awt.Dimension(800, 450));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/setting.png"))); // NOI18N

        editSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png"))); // NOI18N
        editSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editSaveMouseClicked(evt);
            }
        });

        settiingForm.setBackground(new java.awt.Color(68, 189, 141));
        settiingForm.setPreferredSize(new java.awt.Dimension(400, 250));

        jLabel2.setBackground(new java.awt.Color(101, 207, 165));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("image");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("First Name");

        fName.setBackground(java.awt.Color.lightGray);
        fName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        fName.setForeground(new java.awt.Color(102, 83, 23));
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        fName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Email id");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Registration");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Branch");

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Course");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Gender");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Contact");

        upload.setBackground(java.awt.Color.lightGray);
        upload.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        upload.setForeground(new java.awt.Color(102, 83, 23));
        upload.setText("Change");
        upload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadMouseClicked(evt);
            }
        });
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });

        contact.setBackground(java.awt.Color.lightGray);
        contact.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        contact.setForeground(new java.awt.Color(102, 83, 23));

        gender.setBackground(java.awt.Color.lightGray);
        gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gender.setForeground(new java.awt.Color(102, 83, 23));
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your gender?", "Male", "Female", "Other" }));

        regNo.setBackground(java.awt.Color.lightGray);
        regNo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        regNo.setForeground(new java.awt.Color(102, 83, 23));

        email.setBackground(java.awt.Color.lightGray);
        email.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        email.setForeground(new java.awt.Color(102, 83, 23));

        pswd.setBackground(java.awt.Color.lightGray);
        pswd.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        pswd.setForeground(new java.awt.Color(102, 83, 23));

        uName.setBackground(java.awt.Color.lightGray);
        uName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        uName.setForeground(new java.awt.Color(102, 83, 23));

        lName.setBackground(java.awt.Color.lightGray);
        lName.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lName.setForeground(new java.awt.Color(102, 83, 23));

        course.setBackground(java.awt.Color.lightGray);
        course.setForeground(new java.awt.Color(102, 83, 23));
        course.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your Course?", "B.Tech", "M.Tech", "MCA", "Ph.D", "MBA", "MSw", "Other" }));

        branch.setBackground(java.awt.Color.lightGray);
        branch.setForeground(new java.awt.Color(102, 83, 23));
        branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your Branch?", "CSE", "IT", "ME", "ECE", "EE", "CE", "CHEMICAL", "BIOTECH", "Other" }));

        year.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        year.setForeground(new java.awt.Color(255, 255, 255));
        year.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        year.setText("Year");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Authentication Type");

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Date Of Birth");

        yearn.setBackground(java.awt.Color.lightGray);
        yearn.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        yearn.setForeground(new java.awt.Color(102, 83, 23));

        dob.setBackground(java.awt.Color.lightGray);
        dob.setForeground(new java.awt.Color(102, 83, 23));

        access.setBackground(java.awt.Color.lightGray);
        access.setForeground(new java.awt.Color(102, 83, 23));
        access.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Your acess type?", "Coordinator", "Member", "Student", "Outsider" }));

        javax.swing.GroupLayout settiingFormLayout = new javax.swing.GroupLayout(settiingForm);
        settiingForm.setLayout(settiingFormLayout);
        settiingFormLayout.setHorizontalGroup(
            settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settiingFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settiingFormLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(year)
                            .addComponent(jLabel17)))
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addComponent(upload, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(lName))
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(settiingFormLayout.createSequentialGroup()
                                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(regNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pswd)
                                    .addComponent(course, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(settiingFormLayout.createSequentialGroup()
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settiingFormLayout.createSequentialGroup()
                                .addComponent(yearn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settiingFormLayout.createSequentialGroup()
                                .addComponent(access, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        settiingFormLayout.setVerticalGroup(
            settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settiingFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(regNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(settiingFormLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upload))
                .addGap(18, 18, 18)
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(year)
                    .addComponent(yearn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(settiingFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(access, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jScrollPane1.setViewportView(settiingForm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(editSave)
                .addGap(65, 65, 65))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(editSave)))
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 92, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed
    
    int click=0;
    
    private void editSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editSaveMouseClicked
        // TODO add your handling code here:
       if(click==0){
           editSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save.png")));
           click++;
           if(focusgained==0){
               fillUp();
               System.out.println("focusgained "+focusgained);
               focusgained++;
           }
           //DisableElement de = new DisableElement(settiingForm);
           de.enableComponents(settiingForm, true);
           uName.setEnabled(false);
           pswd.setEnabled(false);
           
           
       }
       else{
           editSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit.png")));
           click--;
           
           //JDialog.setDefaultLookAndFeelDecorated(true);
            //JOptionPane.showConfirmDialog(null, "Your changes are saved !", "Status", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
            //if(changes!=0)
                setValues();
           //DisableElement de = new DisableElement(settiingForm);
           de.enableComponents(settiingForm, false);
       }
        
    }//GEN-LAST:event_editSaveMouseClicked

    private void fNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fNameKeyPressed

    private void uploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadMouseClicked

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        //if(focusgained==0){
          //  fillUp();
        //}
    }//GEN-LAST:event_formFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> access;
    private javax.swing.JComboBox<String> branch;
    public javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> course;
    private org.jdesktop.swingx.JXDatePicker dob;
    private javax.swing.JLabel editSave;
    public javax.swing.JTextField email;
    public javax.swing.JTextField fName;
    public javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField lName;
    private java.awt.Label label2;
    public javax.swing.JTextField pswd;
    public javax.swing.JTextField regNo;
    private javax.swing.JPanel settiingForm;
    public javax.swing.JTextField uName;
    public javax.swing.JButton upload;
    private javax.swing.JLabel year;
    public javax.swing.JTextField yearn;
    // End of variables declaration//GEN-END:variables
}
